export default [
  {
    prop: 'src',
    desc: '默认图片src',
    type: 'String',
    enum: '-',
    default: '',
  },
  {
    prop: 'accept',
    desc: '接受上传的文件类型',
    type: 'String',
    enum: '-',
    default: 'image/*',
  },
  {
    prop: 'title',
    desc: '弹出层标题',
    type: 'String',
    enum: '-',
    default: '图片选择',
  },
  {
    prop: 'width',
    desc: '弹出层宽度',
    type: 'String',
    enum: '-',
    default: '600px',
  },
  {
    prop: 'close-on-click-modal',
    desc: '是否可以通过点击 modal 关闭 Dialog',
    type: 'Boolean',
    enum: '-',
    default: 'false',
  },
  {
    prop: 'visible',
    desc: '是否显示 Dialog，支持 .sync 修饰符',
    type: 'Boolean',
    enum: '-',
    default: 'false',
  },
  {
    prop: 'size',
    desc: '表单尺寸',
    type: 'String / Number',
    enum: 'large / medium / small / mini',
    default: 'small',
  },
  {
    prop: 'types',
    desc: '支持的图片上传类型',
    type: 'Array',
    enum: '-',
    default: '[\'web\', \'device\']',
  },
  {
    prop: 'default-type',
    desc: '默认图片上传类型',
    type: 'String',
    enum: 'web / device',
    default: 'device',
  },
  {
    prop: 'disabled',
    desc: '是否禁用',
    type: 'Boolean',
    enum: '-',
    default: 'false',
  },
  {
    prop: 'name',
    desc: '上传的文件字段名',
    type: 'String',
    enum: '-',
    default: 'file',
  },
  {
    prop: 'action',
    desc: '必选参数，上传的地址',
    type: 'String',
    enum: '-',
    default: '-',
  },
  {
    prop: 'headers',
    desc: '设置上传的请求头部',
    type: 'Object',
    enum: '-',
    default: '-',
  },
  {
    prop: 'on-success',
    desc: '文件上传成功时的钩子，必须通过done回传src',
    type: 'Function({response, file, fileList}, done)',
    enum: '-',
    default: '-',
  },
  {
    prop: 'placeholder',
    desc: '图片输入框占位文本',
    type: 'String',
    enum: '-',
    default: 'http://asseek.com/image.jpg',
  },
  {
    prop: 'required',
    desc: 'src是否必须',
    type: 'Boolean',
    enum: '-',
    default: 'false',
  },

];