export default [
  {
    prop: 'loading',
    desc: '是否在view层上显示Loading 加载',
    type: 'Boolean',
    enum: '-',
    default: 'false',
  },
  {
    prop: 'loading-text',
    desc: '显示在加载图标下方的加载文案',
    type: 'String',
    enum: '-',
    default: '数据加载中',
  },
  {
    prop: 'center',
    desc: '页面居中配置',
    type: 'Boolean / Number / String',
    enum: '-',
    default: 'false',
  },
  {
    prop: 'scroll-record',
    desc: '是否记录滚动条高度，需要keep-alive',
    type: 'Boolean',
    enum: '-',
    default: 'true',
  },
  {
    prop: 'scroll-record-children',
    desc: '如果ea-view作为路由组件，它的子路由滚动条默认不被记录 这里可以传入子路由组件名 用于记录滚动条高度',
    type: 'String / Array',
    enum: '-',
    default: 'true',
  },
  {
    prop: 'default-class',
    desc: '是否使用默认样式',
    type: 'Boolean',
    enum: '-',
    default: 'true',
  },
  {
    prop: 'padding',
    desc: '页面padding，默认单位px',
    type: 'Number / String',
    enum: '-',
    default: '10',
  },
  {
    prop: 'backtop',
    desc: '是否显示回到顶部按钮',
    type: 'Boolean',
    enum: '-',
    default: 'true',
  },
  {
    prop: 'params-key',
    desc: '子页面主键',
    type: 'String',
    enum: '-',
    default: '-',
  },
  {
    prop: 'body-class',
    desc: '插入后台body的class，标签激活状态下生效',
    type: 'String',
    enum: '-',
    default: '-',
  },
];
